export const ROUTES = {
  HOME: "/",
  SIGN_UP: "/auth/sign-up",
  SIGN_IN: "/auth/sign-in",
  WORKSPACE: "/app/workspaces",
  DASHBOARD: "/app/dashboard",
  APP: "/app",
  CRM: "/app/crm",
  CONTACTS: "/app/contacts",
  LEADS: "/app/leads",
  DEALS: "/app/deals",
  TASKS: "/app/tasks",
  PROJECTS: "/app/projects",
  INVOICES: "/app/invoices",
  PAYMENTS: "/app/payments",
  SETTINGS: "/app/settings",
  USER_MANAGEMENT: "/app/user-management",
  PROFILE: "/app/profile",
  REQUEST_OTP: "/app/request-otp",
};
